### ISSUE TITLE
TextField: Некорректная верстка для слишком длинных значения пропса rightSide 

### ISSUE THREAD

**Issue by const13** [gpn-prototypes/vega-ui#226]
![image](https://user-images.githubusercontent.com/12236762/91970631-a0290280-ed20-11ea-846c-626369e999e1.png)

При указании в пропсе rightSide (TextField control) слишком длинного значения, div с классами "TextField-Side TextField-Side_position_right" выходит за рамки текстового поля и блокирует ввод значения.

Также стоит отметить, что TextField находится внутри VegaForm.Row, который описан дополнительными стилями {display: grid; grid-template-columns: 60% 30%}. Т.е родительский контейнер для TextField'a ограничен по ширине.

**Comment by maksim-kononov-csssr** [comment]
С нашей стороны мы только [реэкспортим компонент](https://github.com/gpn-prototypes/vega-ui/blob/master/packages/components/text-field/src/TextField.tsx), я думаю исправлять нужно в consta-uikit.
Завез issue: https://github.com/gazprom-neft/consta-uikit/issues/381

**Comment by maksim-kononov-csssr** [comment]
Исправили. Версия vega-ui - 2.13.3, версия vega-text-field - 0.1.8
